service: kaggle-automation

frameworkVersion: '3'

provider:
  name: aws
  runtime: dotnet6

package:
  individually: true

functions:
  kaggleIntegration:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello

    # you can add packaging information here
    package:
      artifact: bin/Release/net6.0/hello.zip

