

service: kaggle-automation
# app and org for use with dashboard.serverless.com
#app: your-app-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: dotnet6

package:
  individually: true

functions:
  kaggleIntegration:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello

    # you can add packaging information here
    package:
      artifact: bin/Release/net6.0/hello.zip

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
